halleycarleton/Notion

- .eslintrc.json
- client/.eslintrc.json
Reducing how strict the .eslintrc files are.
> Reducing eslint strictness

- package.json
- scripts/seed.js
- scripts/test.js
- server/lib/utils/random.js
- server/models/index.js
- yarn.lock
> 19 seed file

- client/Routes.jsx
- client/actions/board.js
- client/components/Board.jsx
- client/constants.js
- client/containers/BoardContainer.js
- client/reducers/boardReducer.js
- client/styles/components/_board.scss
- client/styles/main.scss
- server/routes/api/board.js
> 3 board container

- scripts/seed.js
Improving seed file to include associations between notes and users.
> Associating notes with users in seed file

- server/__test__/routes/api/note.spec.js
- server/routes/api/index.js
- server/routes/api/note.js
> 14 note api routes

- client/constants.js
- client/reducers/noteReducer.js
- client/reducers/rootReducer.js
> Adding Note Reducer

- client/components/Board.js
- client/components/Table.js
- client/styles/components/_board.scss
- client/styles/components/_table.scss
- client/styles/main.scss
I'm going to shut down the board branch since I'm done with it and now working solely on the table. Will create a new table branch.
> board finished, working on table

- client/__tests__/actions/note.spec.js
- client/actions/note.js
- client/reducers/noteReducer.js
- package.json
- yarn.lock
> 17 note action creator

- scripts/seed.js
- server/models/note.js
- server/routes/api/note.js
> 48 note coords schema

- client/containers/CreateNoteContainer.js
- client/reducers/noteBoardReducer.js
- server/routes/api/board.js
> 11 board crud routes

- client/components/Note.js
- client/components/NoteWrapper.js
- client/containers/NoteBoardContainer.js
- client/reducers/noteReducer.js
color fix and noteboard reduxer fix
> fixed noteboard

- client/Routes.jsx
- client/components/Navbar.js
- client/containers/ParticipantsContainer.js
- client/styles/components/_participants.scss
- client/styles/main.scss
- client/utils/stringHash.js
- package.json
- yarn.lock
- participant component
- shorthash and random room name generator
> Participants component

- client/components/ColorPicker.js
- client/components/CreateNote.js
- client/components/Note.js
- client/containers/CreateNoteContainer.js
- client/containers/ViewNoteContainer.js
- client/styles/components/_color-picker.scss
- client/styles/main.scss
- client/styles/objects/_aspect-ratio.scss
- package.json
- yarn.lock
> 53 color picker

- client/Routes.jsx
- client/actions/note.js
- client/actions/socketio.js
- client/actions/user.js
- client/components/CreateNote.js
- client/components/Note.js
- client/containers/CreateNoteContainer.js
- client/reducers/userReducer.js
- client/utils/stringHash.js
> Connecting createNote component to sockets

- client/Routes.jsx
- client/actions/note.js
- client/components/CustomDragLayer.js
- client/components/DraggableNote.js
- client/components/Index.js
- client/containers/CustomDragLayerContainer.js
- client/containers/NoteBoardContainer.js
- client/containers/SocketIOContainer.js
- client/reducers/noteReducer.js
- package.json
- server/sockets/index.js
self-merging as I made only 2 changes to 2 lines in index.js
> 87 dnd touch

- client/actions/note.js
- client/actions/socketio.js
- client/containers/NoteBoardContainer.js
fixed websocket. Self-merging.
> 97 fix websockets

- client/actions/socketio.js
> Minor changes websocket

- client/actions/note.js
- client/containers/NoteBoardContainer.js
fixed board rooms and gave participants access to move notes (unifies board for all users).
> issue 101 fixed board rooms and unified board across users

- lib/utils/random.js
Fixing random string generator
> Fixing random string generator isuue with special chars

- client/actions/socketio.js
- server/sockets/index.js
> Note coords

- client/components/CreateNote.js
- client/styles/components/_navbar.scss
> Adding flick functionality

- client/components/Note.js
- yarn.lock
Adding a fallback color for notes to prevent errors when no props passed in.
> Adding fallback color for the note component

- client/components/Note.js
- client/components/NoteDragPreview.js
- client/components/NoteWrapper.js
- client/styles/components/_note.scss
> Styling notes (first round)
